package com.mss.surrealdbspringbootstarter.mapping;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a {@code List} field as a SurrealDB <em>record-link array</em> — an
 * ordered collection of {@code RecordId}s stored directly inside the owning
 * record, each pointing to a related record in another (or the same) table.
 *
 * <p>This is the multi-valued counterpart of {@link Link}.  All the same
 * rules around field types and auto-FETCH apply:
 *
 * <ul>
 *   <li>{@code List<RecordId> fieldName} — each element is a raw id.</li>
 *   <li>{@code List<TargetEntityClass> fieldName} — when {@link #fetch()} is
 *       {@code true}, SurrealDB embeds the full linked documents and the SDK
 *       deserialises them into the declared element type.  When {@code false},
 *       the SDK returns a list of objects with only their {@code @Id} fields
 *       populated.</li>
 * </ul>
 *
 * <h3>Auto-FETCH</h3>
 * <p>When {@link #fetch()} is {@code true} the field name is included in the
 * {@code FETCH} clause generated by
 * {@link com.mss.surrealdbspringbootstarter.core.SurrealTemplate#findById} and
 * {@link com.mss.surrealdbspringbootstarter.core.SurrealTemplate#findAll}.
 * When {@code false} (the default) those methods use a SurQL subquery to
 * ensure string record-ids are returned as JSON objects, allowing
 * deserialisation into the declared element type.
 *
 * <h3>Usage</h3>
 * <pre>
 * {@literal @}Table("person")
 * public class Person {
 *
 *     {@literal @}Id
 *     public String id;
 *
 *     {@literal @}LinkList(fetch = true)
 *     public List&lt;Person&gt; friends;
 * }
 * </pre>
 *
 * @see Link
 * @see com.mss.surrealdbspringbootstarter.core.SurrealTemplate
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface LinkList {

    /**
     * When {@code true} this field's name is appended to the {@code FETCH}
     * clause generated by {@code SurrealTemplate} query methods.
     * Defaults to {@code false}.
     */
    boolean fetch() default false;
}
