package com.mss.springdata.surrealdb.mapping;

import com.mss.springdata.surrealdb.core.SurrealTemplate;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field as a SurrealDB <em>record link</em> — a direct pointer to a
 * single related record stored as a {@code RecordId} inside the owning record.
 *
 * <p>Record links are the lightweight alternative to full graph edges.  The
 * owning record stores only the target's {@code RecordId}; no separate edge
 * table is created.
 *
 * <h2>Field type choices</h2>
 * <ul>
 *   <li>{@code RecordId fieldName} — the field stores the raw id.  The linked
 *       record is <em>not</em> hydrated automatically even when
 *       {@link #fetch()} is {@code true}; only the id is present.</li>
 *   <li>{@code TargetEntityClass fieldName} — when {@link #fetch()} is
 *       {@code true} the FETCH clause causes SurrealDB to embed the full linked
 *       document in the response, which the SDK then deserialises into the
 *       declared type.  When {@code false}, the SDK returns an instance of the
 *       declared type with only its {@code @Id} field populated.</li>
 * </ul>
 *
 * <h2>Auto-FETCH</h2>
 * <p>When {@link #fetch()} is {@code true} the field name is included in an
 * automatically generated {@code FETCH} clause by
 * {@link SurrealTemplate#findById} and
 * {@link SurrealTemplate#findAll}.
 * When {@code false} (the default) those methods use a SurQL projection to
 * ensure the string record-id is returned as a JSON object, allowing
 * deserialisation into the declared type.
 *
 * <h2>Usage</h2>
 * <pre>
 * {@literal @}Table("person")
 * public class Person {
 *
 *     {@literal @}Id
 *     public String id;
 *
 *     // stored as bare RecordId; resolved automatically on read
 *     {@literal @}Link(fetch = true)
 *     public Company company;
 * }
 * </pre>
 *
 * @see LinkList
 * @see SurrealTemplate
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface Link {

    /**
     * When {@code true} this field's name is appended to the {@code FETCH}
     * clause generated by {@code SurrealTemplate} query methods.
     * Defaults to {@code false} to avoid unintended n+1 suppression.
     */
    boolean fetch() default false;
}
